# Generated at (UTC): 2026-06-01T11:37:30Z

# Higanoneko's ProxyRules - Box4Root 复杂配置
# 如不会配置，也可自行寻找懒人配置，例如(Surfing 模块配置)：https://raw.githubusercontent.com/GitMetaio/Surfing/refs/heads/main/box_bll/clash/config.yaml

proxy-providers:
  proxy1:
    type: http
    url: "填写订阅链接"
    path: ./proxy_provider/proxy1.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://cp.cloudflare.com
      interval: 300
      timeout: 1000
      tolerance: 100
  # 多订阅按照下面照葫芦画瓢即可
  # proxy2:
  #   type: http
  #   url: "填写订阅链接"
  #   path: ./proxy_provider/proxy2.yaml
  #   interval: 3600
  #   health-check:
  #     enable: true
  #     url: https://cp.cloudflare.com
  #     interval: 300
  #     timeout: 1000
  #     tolerance: 100
mixed-port: 56365
redir-port: 9797
tproxy-port: 9898
mode: Rule
bind-address: '*'
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: error
find-process-mode: always
# global-client-fingerprint: random
external-controller: 0.0.0.0:9090
external-ui: ./dashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
geodata-mode: false
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"
tun:
  enable: false
  device: umihomo
  stack: mixed
  dns-hijack: ['any:53', 'tcp://any:53']
  udp-timeout: 300
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
profile:
  store-selected: true
  store-fake-ip: true
proxies:
  - {name: DNS_Hijack, type: dns}
# Normal Start From Here
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  default-nameserver:
    - 119.29.29.29
    - '2402:4e00::'
    - 1.1.1.1
    - 2606:4700:4700::1111
    - 8.8.8.8
    - 2001:4860:4860::8888
  direct-nameserver:
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver:
    - https://doh.pub/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - '*.netease.com'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - '*.tencent.com'
    - '*.qq.com'
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - '*.xiami.com'
    - '*.xiaomi.com'
    - '*.mi.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - stun.*.*.*.*
    - heartbeat.belkin.com
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.direct'
    - cable.auth.com
    - network-test.debian.org
    - detectportal.firefox.com
    - resolver1.opendns.com
    - '*.xboxlive.com'
    - global.turn.twilio.com
    - global.stun.twilio.com
    - app.yinxiang.com
    - injections.adguard.org
    - local.adguard.org
    - localhost.*.qq.com
    - localhost.*.weixin.qq.com
    - '*.logon.battle.net'
    - '*.blzstatic.cn'
    - '*.mcdn.bilivideo.cn'
    - '*.cmpassport.com'
    - id6.me
    - open.e.189.cn
    - opencloud.wostore.cn
    - id.mail.wo.cn
    - mdn.open.wo.cn
    - hmrz.wo.cn
    - nishub1.10010.com
    - enrichgw.10010.com
    - '*.wosms.cn'
    - '*.jegotrip.com.cn'
    - '*.icitymobile.mobi'
    - '*.pingan.com.cn'
    - '*.cmbchina.com'
    - '*.10099.com.cn'
    - '*.microdone.cn'
sniffer:
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
proxy-groups:
  - name: 选择代理
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 其他节点
      - 手动选择
      - DIRECT
  - name: 手动选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Round_Robin_1.png
    include-all: true
    type: select
  - name: AI
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AI.png
    type: select
    proxies: &a1
      - 选择代理
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 其他节点
      - 手动选择
      - 直接连接
  - name: Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies: *a1
  - name: YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies: *a1
  - name: Netflix
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
    type: select
    proxies: *a1
  - name: Spotify
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    type: select
    proxies: *a1
  - name: TikTok
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png
    type: select
    proxies: *a1
  - name: Steam
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    type: select
    proxies: *a1
  - name: Game
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    type: select
    proxies: *a1
  - name: E-Hentai
    icon: https://cdn.jsdelivr.net/gh/Higanoneko/CustomProxyRuleset@main/Icons/Ehentai.png
    type: select
    proxies: *a1
  - name: PornSite
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Pornhub.png
    type: select
    proxies: *a1
  - name: US Media
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    type: select
    proxies:
      - 美国节点
      - 选择代理
      - 手动选择
      - 直接连接
  - name: Taiwan Media
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    type: select
    proxies:
      - 台湾节点
      - 选择代理
      - 手动选择
      - 直接连接
  - name: Japan Media
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    type: select
    proxies:
      - 日本节点
      - 选择代理
      - 手动选择
      - 直接连接
  - name: Global Media
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/DomesticMedia.png
    type: select
    proxies: *a1
  - name: Apple
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png
    type: select
    proxies:
      - 直接连接
      - 选择代理
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 其他节点
      - 手动选择
  - name: Microsoft
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png
    type: select
    proxies:
      - 直接连接
      - 选择代理
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 其他节点
      - 手动选择
  - name: Google
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies: *a1
  - name: Google FCM
    icon: https://cdn.jsdelivr.net/gh/Higanoneko/CustomProxyRuleset@main/Icons/Firebase.png
    type: select
    proxies:
      - Google
      - 直接连接
  - name: Sogou Privacy
    icon: https://cdn.jsdelivr.net/gh/Higanoneko/CustomProxyRuleset@main/Icons/Sougou.png
    type: select
    proxies:
      - 直接连接
      - REJECT
  - name: ADBlock
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT-DROP
      - REJECT
      - 直接连接
  - name: 直接连接
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 选择代理
  - name: 香港节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: "(?i)香港|港|HK|hk|Hong Kong|HongKong|Hongkong|Hong kong|hongkong|hong kong|\U0001F1ED\U0001F1F0"
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: 台湾节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: "(?i)台|新北|彰化|TW|Taiwan|TaiWan|Tai wan|Tai Wan|taiwan|tai wan|\U0001F1F9\U0001F1FC"
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: 新加坡节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: "(?i)新加坡|坡|狮城|SG|Singapore|\U0001F1F8\U0001F1EC"
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: 日本节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: "(?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|\U0001F1EF\U0001F1F5"
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: 美国节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: "(?i)美国|美|US|United States|\U0001F1FA\U0001F1F8"
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: 其他节点
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    exclude-filter: "(?i)香港|港|HK|hk|Hong Kong|HongKong|Hongkong|Hong kong|hongkong|hong kong|\U0001F1ED\U0001F1F0|台|新北|彰化|TW|Taiwan|TaiWan|Tai wan|Tai Wan|taiwan|tai wan|\U0001F1F9\U0001F1FC|新加坡|坡|狮城|SG|Singapore|\U0001F1F8\U0001F1EC|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|\U0001F1EF\U0001F1F5|美国|美|US|United States|\U0001F1FA\U0001F1F8"
    type: select
  - name: GLOBAL
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    type: select
    proxies: *a1
rule-providers:
  AI:
    type: http
    behavior: classical
    format: yaml
    interval: 86400
    url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/AI Suite.yaml
    path: ./ruleset/AI.yaml
  Telegram:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/telegram.txt
    path: ./ruleset/Telegram.list
  YouTube:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
    path: ./ruleset/YouTube.list
  YouTubeMusic:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.list
    path: ./ruleset/YouTubeMusic.list
  Netflix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
    path: ./ruleset/Netflix.list
  TikTok:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
    path: ./ruleset/TikTok.list
  Spotify:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
    path: ./ruleset/Spotify.list
  Steam:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
    path: ./ruleset/Steam.list
  Game:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list
    path: ./ruleset/Game.list
  E-Hentai:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EHGallery/EHGallery.list
    path: ./ruleset/E-Hentai.list
  PornSite:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/Higanoneko/CustomProxyRuleset/main/PornSite/PornSite.list
    path: ./ruleset/PornSite.list
  Stream_US:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/stream_us.txt
    path: ./ruleset/Stream_US.list
  Stream_TW:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/stream_tw.txt
    path: ./ruleset/Stream_TW.list
  Stream_JP:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/stream_jp.txt
    path: ./ruleset/Stream_JP.list
  Stream_Global:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/stream.txt
    path: ./ruleset/Stream_Global.list
  Apple:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
    path: ./ruleset/Apple.list
  Microsoft:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
    path: ./ruleset/Microsoft.list
  Google:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
    path: ./ruleset/Google.list
  GoogleFCM:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
    path: ./ruleset/Google FCM.list
  SogouPrivacy:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt
    path: ./ruleset/SogouInput.list
  ADBlock:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://adrules.top/adrules-mihomo.mrs
    path: ./ruleset/ADBlock.mrs
  LocalNetwork:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
    path: ./ruleset/LocalNetwork.list
  LocalNetworkIP:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
    path: ./ruleset/LocalNetworkIP.list
  Furrybar:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/Higanoneko/CustomProxyRuleset/main/Furrybar/Furrybar.list
    path: ./ruleset/Furrybar.list
  Playhorny:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/Higanoneko/CustomProxyRuleset/main/Playhorny/Playhorny.list
    path: ./ruleset/Playhorny.list
  Nikke:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.githubusercontent.com/Higanoneko/CustomProxyRuleset/main/Nikke/Nikke.list
    path: ./ruleset/Nikke.list
rules:
  - DST-PORT,53,DNS_Hijack
  - RULE-SET,AI,AI
  - RULE-SET,Telegram,Telegram
  - RULE-SET,YouTube,YouTube
  - RULE-SET,YouTubeMusic,YouTube
  - RULE-SET,Netflix,Netflix
  - RULE-SET,TikTok,TikTok
  - RULE-SET,Spotify,Spotify
  - RULE-SET,Steam,Steam
  - RULE-SET,Game,Game
  - RULE-SET,E-Hentai,E-Hentai
  - RULE-SET,PornSite,PornSite
  - RULE-SET,Stream_US,US Media
  - RULE-SET,Stream_TW,Taiwan Media
  - RULE-SET,Stream_JP,Japan Media
  - RULE-SET,Stream_Global,Global Media
  - RULE-SET,Apple,Apple
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Google,Google
  - RULE-SET,GoogleFCM,Google FCM
  - RULE-SET,SogouPrivacy,Sogou Privacy
  - RULE-SET,ADBlock,ADBlock
  - RULE-SET,LocalNetwork,DIRECT
  - RULE-SET,LocalNetworkIP,DIRECT
  - RULE-SET,Furrybar,PornSite
  - RULE-SET,Playhorny,Game
  - RULE-SET,Nikke,Game
  - GEOIP,CN,直接连接
  - MATCH,选择代理
